### PR TITLE
complete targets binding

### PR DESCRIPTION
**Pull request by yosefm**
Finish the Target accessors, add possibilities to manipulate them from Python, and use write_targets to complete the I/O side.

### CODE REVIEW

**Comment by alexlib** [comment]
One failure, seemingly not related to the targets: 
```
Alexs-MacBook-Pro:py_bind alex$ cd test/
Alexs-MacBook-Pro:test alex$ nosetests
.F......
======================================================================
FAIL: Filling a calibration object by reading ori files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alex/Documents/OpenPTV/alexlib/py_bind/test/test_calibration_binding.py", line 30, in test_Calibration_instantiation
    self.assertTrue(filecmp.cmp(self.input_ori_file_name, self.output_ori_file_name, 0))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 8 tests in 0.065s

FAILED (failures=1)
```

**Comment by alexlib** [comment]
The error reported above is due to the file printed in a slightly different format compared to the original file: 
```
105.26320000 102.74580000 403.88220000
    -0.23832910  0.24428100  0.05525770

     0.9688305 -0.0535899  0.2418587
    -0.0033422  0.9734041  0.2290704
    -0.2477021 -0.2227388  0.9428845

     -2.4742   3.2567
    100.0000

       0.000100000000000    0.000010000000000   150.000000000000000

```

**Comment by yosefm** [comment]
Unrelated. PR #67 fixes this, you can see that th relevant file is changed there.

**Comment by alexlib** [comment]
great. recommend to merge

**Pull request merged**
