### PR TITLE
fixed incompatible pointer warnings

### PR DESCRIPTION
**Pull request by alexlib**

### CODE REVIEW

**Comment by yosefm** [comment]
The split test fails because you didn't update the addressing of the split halfs of the image in the ``fail_unless()`` calls.

**Comment by alexlib** [comment]
fixed the split test

**Comment by yosefm** [comment]
Alex, you don't have to make a new PR every time you push to the same branch of an existing PR. It's a headache for me and it loses the discussion.

**Comment by yosefm** [comment]
Anyway, now the test passes and I'm for merging.

**Pull request merged**
