### PR TITLE
resubmission of sort grid with a new assignment algorithm

### PR DESCRIPTION
**Pull request by alexlib**
resubmission of sort grid with a new assignment algorithm, works for both ```nfix``` larger or smaller than ```num``` and assigns points to the real neighbours

### CODE REVIEW

**Comment by alexlib** [comment]
There is one important change from the old version - the the pix.pnr is now just a row number of the dot in the calibration file and not it's ID or anything else.

**Comment by yosefm** [comment]
Alex, the orientation routines expect the pix and fix arrays to be in the same order, that is pix[j] is the closest point to fix[j]. I don't see where this reordering happens in this code. Did you intend to change this and have the future orientation routines expect a different input?

**Comment by yosefm** [comment]
The single pass sorting saves the nearest-neighbour linear target search for each known point. On the other hand it considerably complicates the code where speed isn't very important. I would reconsider the older mechanism with some improvements.

**Comment by alexlib** [comment]
see #82

**Comment by alexlib** [comment]
I think we agreed to keep the new "old" form - using only neighbour_pix in one cycle and increase/decrease the size of the array to nfix by returning a new target sorted_pix[] See #83

**Pull request closed without merging**
