### PR TITLE
PR61 bugfix

### PR DESCRIPTION
**Pull request by yosefm**
Some additions to PR #61. Unfortunately I based this branch on the latest head s oit would be a mess to propose a PR into Alex's branch, so I'm just opening a clean PR with both our changes.

### CODE REVIEW

**Comment by yosefm** [comment]
Can I merge?

**Comment by alexlib** [comment]
go ahead

**Comment by yosefm** [comment]
Ah, sorry, I forgot I promissed a proper test. Coming soon.

**Comment by yosefm** [comment]
Ok, please test now,

**Comment by alexlib** [comment]
now it fails faithfully :+1: 

10: Test command: /Users/alex/Documents/openptv/alexlib/liboptv/build/tests/check_imgcoord
10: Test timeout computed to be: 9.99988e+06
10: Running suite(s): Imgcoord
10: 50%: Checks: 4, Failures: 2, Errors: 0
10: /Users/alex/Documents/openptv/alexlib/liboptv/tests/check_imgcoord.c:65:F:Image coordinates all-air camera moved:test_flat_decentered_cam:0: Assertion 'x == 0' failed
10: /Users/alex/Documents/openptv/alexlib/liboptv/tests/check_imgcoord.c:98:F:Multilayer image coordinates, no distortion:test_flat_multilayer:0: Assertion 'x == 0' failed
10/10 Test #10: check_imgcoord ...................***Failed    0.01 sec

**Comment by alexlib** [comment]
should I test it after merging all the previous pull requests or directly from alex61_bugfix ?

**Comment by alexlib** [comment]
the problem is (x == 0) test. If we replace it by fabs(x) < EPS it passes for EPS = 1e-6. see the patch 
https://gist.github.com/alexlib/40bdefe31cd5e055f7c7

**Comment by alexlib** [comment]
see pull request to your repository - the tests fail on Mac, although the values are very close to zero.

**Pull request merged**
